export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#23262F] text-white px-6 py-16 max-w-3xl mx-auto">
      <h1 className="text-3xl font-bold mb-2 font-sora">Terms of Service</h1>
      <p className="text-sm text-gray-400 mb-10">Last updated: July 31, 2026</p>

      <section className="flex flex-col gap-8 text-sm text-gray-300 leading-relaxed">
        <div>
          <h2 className="text-white font-semibold text-base mb-2">1. Acceptance</h2>
          <p>By using Wingspan and Design Evolution, you agree to these terms. If you do not agree, please do not use the service.</p>
        </div>

        <div>
          <h2 className="text-white font-semibold text-base mb-2">2. Service description</h2>
          <p>Wingspan is an AI-powered career intelligence tool for designers. It analyses your resume and generates a personalised Blueprint. Design Evolution is a learning platform that helps designers grow through structured experiences.</p>
        </div>

        <div>
          <h2 className="text-white font-semibold text-base mb-2">3. Your content</h2>
          <p>You retain ownership of any content you upload (resumes, portfolio links). By uploading, you grant us a limited licence to process that content for the purpose of generating your Blueprint. We do not claim ownership of your career data.</p>
        </div>

        <div>
          <h2 className="text-white font-semibold text-base mb-2">4. AI-generated content</h2>
          <p>Blueprints and career recommendations are generated by AI and are provided for informational purposes only. They do not constitute professional career advice. We make no guarantees about the accuracy or completeness of AI-generated content.</p>
        </div>

        <div>
          <h2 className="text-white font-semibold text-base mb-2">5. Acceptable use</h2>
          <p>You agree not to misuse the service, attempt to reverse-engineer the AI pipeline, scrape content, or use the platform for any unlawful purpose.</p>
        </div>

        <div>
          <h2 className="text-white font-semibold text-base mb-2">6. Availability</h2>
          <p>We strive for high availability but do not guarantee uninterrupted service. We may update or discontinue features at any time.</p>
        </div>

        <div>
          <h2 className="text-white font-semibold text-base mb-2">7. Limitation of liability</h2>
          <p>To the maximum extent permitted by law, Wingspan is provided "as is" without warranties of any kind. We are not liable for any indirect or consequential damages arising from your use of the service.</p>
        </div>

        <div>
          <h2 className="text-white font-semibold text-base mb-2">8. Contact</h2>
          <p>For questions about these terms, contact us at <a href="mailto:uxbyamit@gmail.com" className="text-[#B6FF2E] underline">uxbyamit@gmail.com</a></p>
        </div>
      </section>
    </div>
  )
}
