// lib/export.ts
// Generates a Notion-importable Markdown document from the Blueprint
import { Blueprint } from '@/types/wingspan'

export function exportToNotionMarkdown(blueprint: Blueprint, selectedPath: string | null): string {
  const { profileMap, strengths, futurePaths, gaps, actions, roadmapMilestones, positioning } = blueprint
  const path = futurePaths.find(p => p.title === selectedPath) ?? futurePaths[0]
  const now = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })

  const lines: string[] = [
    `# Future Self Blueprint™`,
    `> Generated by Wingspan · ${now}`,
    ``,
    `---`,
    ``,
    `## About`,
    ``,
    profileMap.identityStatement,
    ``,
    profileMap.careerEvolution,
    ``,
    `**Years of experience:** ${profileMap.yearsOfExperience}`,
    `**Industries:** ${profileMap.industries.join(', ')}`,
    `**Domains:** ${profileMap.domains.join(', ')}`,
    ``,
    `---`,
    ``,
    `## Chosen Direction`,
    ``,
    `### ${path?.title ?? 'No path selected'}`,
    ``,
    path?.betRationale ?? path?.whyItFits ?? '',
    ``,
    `| | |`,
    `|---|---|`,
    `| Timeline | ${path?.timeline ?? '—'} |`,
    `| Career Alpha | ${path?.careerAlphaScore ?? '—'} |`,
    `| Career ROI | ${path?.careerROIScore ?? '—'} |`,
    `| Learning Investment | ${path?.learningInvestment ?? '—'} |`,
    ``,
  ]

  // Positioning
  if (positioning) {
    lines.push(`---`, ``, `## Positioning Strategy`, ``)
    lines.push(`**Target Role:** ${positioning.targetRole}`)
    lines.push(`**Target Companies:** ${positioning.targetCompanies.join(', ')}`)
    lines.push(`**Target Identity:** ${positioning.targetIdentity.join(', ')}`)
    lines.push(``)
    lines.push(`> ${positioning.positioningStatement}`)
    lines.push(``)
  }

  // Roadmap
  if (roadmapMilestones && roadmapMilestones.length > 0) {
    lines.push(`---`, ``, `## Growth Roadmap`, ``)
    for (const milestone of roadmapMilestones) {
      lines.push(`### ${milestone.phase}`, ``)
      for (const action of milestone.actions) {
        lines.push(`- [ ] ${action}`)
      }
      if (milestone.hardSkills?.length) {
        lines.push(``, `**Hard Skills:** ${milestone.hardSkills.join(', ')}`)
      }
      if (milestone.softSkills?.length) {
        lines.push(`**Soft Skills:** ${milestone.softSkills.join(', ')}`)
      }
      if (milestone.positioningMoves?.length) {
        lines.push(`**Positioning:** ${milestone.positioningMoves.join(', ')}`)
      }
      lines.push(``)
    }
  }

  // Gap Analysis
  if (gaps && gaps.length > 0) {
    const pathGaps = selectedPath
      ? gaps.filter(g => g.pathway === selectedPath || g.pathway.includes(selectedPath.split('/')[0].trim()))
      : gaps
    if (pathGaps.length > 0) {
      lines.push(`---`, ``, `## Gap Analysis`, ``)
      for (const gap of pathGaps) {
        lines.push(`### ${gap.gapType}`, ``)
        lines.push(`**${gap.whyItMatters}**`, ``)
        lines.push(`*From:* ${gap.currentState}`)
        lines.push(`*To:* ${gap.desiredState}`)
        lines.push(`*Timeline:* ${gap.timeline} · *Effort:* ${gap.effort}`)
        lines.push(``)
        if (gap.objectives?.length) {
          for (const obj of gap.objectives) {
            lines.push(`- [ ] ${obj.text}`)
          }
          lines.push(``)
        }
      }
    }
  }

  // Actions
  const immediate = selectedPath
    ? actions.immediate.filter(a => a.pathway === selectedPath || a.pathway.includes(selectedPath.split('/')[0].trim()))
    : actions.immediate

  if (immediate.length > 0) {
    lines.push(`---`, ``, `## Immediate Actions`, ``)
    for (const action of immediate) {
      lines.push(`### ${action.title}`)
      lines.push(action.description)
      lines.push(`**First step:** ${action.howToStart}`)
      if (action.link) lines.push(`**Resource:** [${action.linkLabel ?? 'Open'}](${action.link})`)
      lines.push(``)
    }
  }

  // Resources
  const resources = selectedPath
    ? actions.resources.filter(r => r.pathway === selectedPath || r.pathway.includes(selectedPath.split('/')[0].trim()))
    : actions.resources

  if (resources.length > 0) {
    lines.push(`---`, ``, `## Resources`, ``)
    for (const res of resources) {
      const urlPart = res.url ? ` — [Open](${res.url})` : ''
      lines.push(`- **${res.title}** *(${res.type})*${urlPart}`)
      if (res.firstStep) lines.push(`  *First step: ${res.firstStep}*`)
    }
    lines.push(``)
  }

  lines.push(`---`, ``, `*Exported from Wingspan — your Future Self Blueprint*`)

  return lines.join('\n')
}

export function downloadMarkdown(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

function escapeHtml(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

function inlineMd(str: string): string {
  return escapeHtml(str)
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/\[(.+?)\]\((.+?)\)/g, '<a href="$2">$1</a>')
}

function markdownToHTMLDocument(markdown: string): string {
  // Convert the markdown subset used by exportToNotionMarkdown to HTML
  const lines = markdown.split('\n')
  const htmlLines: string[] = []
  let inTable = false

  for (const line of lines) {
    if (line.startsWith('# ')) {
      htmlLines.push(`<h1>${escapeHtml(line.slice(2))}</h1>`)
    } else if (line.startsWith('## ')) {
      htmlLines.push(`<h2>${escapeHtml(line.slice(3))}</h2>`)
    } else if (line.startsWith('### ')) {
      htmlLines.push(`<h3>${escapeHtml(line.slice(4))}</h3>`)
    } else if (line.startsWith('> ')) {
      htmlLines.push(`<blockquote>${escapeHtml(line.slice(2))}</blockquote>`)
    } else if (line.startsWith('- [ ] ')) {
      htmlLines.push(`<p class="task">☐ ${escapeHtml(line.slice(6))}</p>`)
    } else if (line.startsWith('- ')) {
      htmlLines.push(`<li>${inlineMd(line.slice(2))}</li>`)
    } else if (line.startsWith('---')) {
      inTable = false
      htmlLines.push(`<hr>`)
    } else if (line.startsWith('|')) {
      if (!inTable) {
        htmlLines.push('<table>')
        inTable = true
      }
      const cells = line.split('|').filter((_, i, a) => i > 0 && i < a.length - 1)
      const isHeader = cells.some(c => /^[-\s]+$/.test(c.trim()))
      if (!isHeader) {
        const tag = htmlLines[htmlLines.length - 1] === '<table>' ? 'th' : 'td'
        htmlLines.push(`<tr>${cells.map(c => `<${tag}>${inlineMd(c.trim())}</${tag}>`).join('')}</tr>`)
      }
    } else {
      if (inTable) { htmlLines.push('</table>'); inTable = false }
      if (line.trim() === '') {
        htmlLines.push('<br>')
      } else {
        htmlLines.push(`<p>${inlineMd(line)}</p>`)
      }
    }
  }
  if (inTable) htmlLines.push('</table>')

  const body = htmlLines.join('\n')

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Future Self Blueprint™</title>
<style>
  body { font-family: system-ui, sans-serif; font-size: 12pt; color: #111; background: #fff; margin: 2cm; }
  h1 { font-size: 20pt; margin-top: 0; page-break-before: avoid; }
  h2 { font-size: 14pt; border-bottom: 1px solid #ddd; padding-bottom: 4px; margin-top: 24px; }
  h3 { font-size: 12pt; font-weight: bold; margin-top: 16px; }
  hr { border: none; border-top: 1px solid #eee; margin: 20px 0; page-break-after: always; }
  blockquote { border-left: 3px solid #ccc; margin: 8px 0; padding-left: 12px; color: #555; font-style: italic; }
  table { border-collapse: collapse; width: 100%; margin: 12px 0; }
  th, td { border: 1px solid #ddd; padding: 6px 10px; text-align: left; font-size: 11pt; }
  th { background: #f5f5f5; font-weight: bold; }
  li { margin: 3px 0; }
  p.task { font-family: monospace; font-size: 11pt; margin: 4px 0; }
  @media print { body { margin: 1.5cm; } }
</style>
</head>
<body>
${body}
</body>
</html>`
}

export function printAsPDF(blueprint: Blueprint, selectedPath: string | null) {
  const md = exportToNotionMarkdown(blueprint, selectedPath)
  const html = markdownToHTMLDocument(md)
  const win = window.open('', '_blank')
  if (!win) return
  win.document.write(html)
  win.document.close()
  win.onafterprint = () => win.close()
  win.print()
}
