// lib/mock-data.ts
// Mock data based on Amit Kumar Tiwari's resume — used when NEXT_PUBLIC_MOCK=true

import { ExtractedCareerData, Blueprint, CareerAlphaIntelligence } from '@/types/wingspan'

export const mockExtractedData: ExtractedCareerData = {
  timeline: [
    {
      id: '1',
      role: 'UX Manager',
      company: 'Accenture',
      startDate: 'Dec 2018',
      endDate: 'Present',
      description: 'Leading Data Governance design track for global Data & AI capability. Led 8x team scaling, airline booking app, telecom enterprise, AI-powered business insights, new insurance app launch.',
      confirmed: false,
    },
    {
      id: '2',
      role: 'UX Design Engineer',
      company: 'Hewlett Packard Enterprise',
      startDate: 'Dec 2015',
      endDate: 'Dec 2018',
      description: 'Designed composable and hybrid cloud management products. Co-defined HPE design system (Grommet.io). Led international user research and usability testing.',
      confirmed: false,
    },
    {
      id: '3',
      role: 'UX Creative Lead',
      company: 'Photon Interactive',
      startDate: 'Jul 2014',
      endDate: 'Dec 2015',
      description: 'E2E design for B2C e-commerce for a leading global publishing group. Founded first-ever design capability and local chapter.',
      confirmed: false,
    },
    {
      id: '4',
      role: 'UX Designer',
      company: 'Infosys Limited',
      startDate: 'Jan 2011',
      endDate: 'Jul 2014',
      description: 'Worked for 20+ client accounts conducting user-research, contextual enquiry, information architecture, low-fi and hi-fi prototyping and visual design.',
      confirmed: false,
    },
  ],
  projects: [
    {
      id: 'p1',
      name: 'Middle Eastern Airline Booking App',
      company: 'Accenture',
      year: '2022',
      industry: 'Aviation',
      platform: 'Mobile',
      audience: 'B2C',
      summary: 'End-to-end experience design for a major Middle Eastern airline booking app',
      impact: '100-day MLP launch, 300K new visitors, 92% engagement boost',
    },
    {
      id: 'p2',
      name: 'Data Governance Design Track',
      company: 'Accenture',
      year: '2023',
      industry: 'Data & AI',
      platform: 'Enterprise',
      audience: 'B2B',
      summary: 'AI-powered business insights for 360° value proposition',
      impact: 'RFPs resulting in 100% conversion',
    },
    {
      id: 'p3',
      name: 'Telecom Multi-Channel Enterprise App',
      company: 'Accenture',
      year: '2021',
      industry: 'Telecom',
      platform: 'Web',
      audience: 'B2B',
      summary: 'Experience strategy for multi-channel enterprise business',
      impact: '$446K in cost savings',
    },
    {
      id: 'p4',
      name: 'Cloud Migration Cost Optimiser',
      company: 'Accenture',
      year: '2022',
      industry: 'Cloud',
      platform: 'Enterprise SaaS',
      audience: 'B2B',
      summary: 'Scaled design team 8x for cloud product',
      impact: 'Optimises cloud migration costs by nearly 30%',
    },
    {
      id: 'p5',
      name: 'New Insurance App',
      company: 'Accenture',
      year: '2023',
      industry: 'Insurance',
      platform: 'Mobile',
      audience: 'B2C',
      summary: 'Design and launch of insurance app for Indian consumers',
      impact: 'Catering to diverse user base',
    },
    {
      id: 'p6',
      name: 'HPE Cloud Management Suite',
      company: 'Hewlett Packard Enterprise',
      year: '2017',
      industry: 'Cloud',
      platform: 'Enterprise SaaS',
      audience: 'B2B',
      summary: 'Composable and hybrid cloud management products',
      impact: 'Improved product adoption through cross-collaborative design practices',
    },
    {
      id: 'p7',
      name: 'HPE Grommet Design System',
      company: 'Hewlett Packard Enterprise',
      year: '2016',
      industry: 'Design Systems',
      platform: 'Web',
      audience: 'B2B',
      summary: 'Co-defined key components for HPE\'s design system (Grommet.io)',
      impact: 'Impacted brand consistency and efficiency across HPE products',
    },
  ],
  skills: [
    'Experience Strategy', 'Design Leadership', 'UX Research', 'Information Architecture',
    'Wireframing', 'Prototyping', 'Usability Testing', 'Design Systems', 'DesignOps',
    'Generative AI', 'Product Mindset', 'MLP Definition', 'Figma', 'Framer', 'Adobe CC',
    'Miro', 'FigJam', 'JIRA', 'Notion', 'Google Analytics', 'Stakeholder Management',
    'Team Building', 'Mentoring', 'Workshop Facilitation',
  ],
  education: [
    { institution: 'West Bengal University of Technology', degree: 'Bachelor of Technology, Computer Science & Engg', year: '2010' },
    { institution: 'UXCEL', degree: 'UX Designer Certification — Verified Designer, score 99 (Top 1% worldwide)', year: '2022' },
    { institution: 'Google Coursera', degree: 'Foundation of UX', year: '2022' },
    { institution: 'UX Academy (Infosys)', degree: 'UX Certification', year: '2012' },
  ],
  rawText: 'Amit Kumar Tiwari — UX Manager with 13+ years of experience across Accenture, HPE, Photon Interactive, and Infosys.',
}

export const mockBlueprint: Blueprint = {
  profileMap: {
    identityStatement: 'You are a rare hybrid — a design strategist who thinks like a product leader and builds like an engineer. Over 13 years, you\'ve consistently operated at the intersection of complexity, systems, and human experience.',
    yearsOfExperience: 13,
    industries: ['Data & AI', 'Aviation', 'Cloud', 'Telecom', 'Insurance', 'FinTech', 'E-commerce'],
    platforms: ['Enterprise SaaS', 'Mobile', 'Web', 'Design Systems'],
    domains: ['Experience Strategy', 'Design Leadership', 'Generative AI', 'DesignOps', 'Product Design'],
    careerEvolution: 'You began as a craftsman of interfaces at Infosys, sharpened into a creative lead at Photon, then stepped fully into strategic territory at HPE building foundational design systems. At Accenture, you\'ve evolved into a design executive — scaling teams, defining capability, and anchoring AI-first experiences for global enterprises. Your arc is unmistakably upward: from hands-on design to organisational transformation.',
    metrics: [
      { label: 'Years Experience', value: 13, highlight: true },
      { label: 'Projects', value: 58, highlight: true },
      { label: 'Industries', value: 7, highlight: true },
      { label: 'Role Transitions', value: 6, highlight: false },
      { label: 'Tools Mastered', value: 21, highlight: false },
      { label: 'Leadership Positions', value: 4, highlight: false },
    ],
  },
  strengths: [
    {
      name: 'Systems Thinking',
      confidence: 95,
      evidence: 'Co-defined Grommet.io at HPE, anchored Data Governance design track at Accenture, built DesignOps frameworks across 4 organisations',
      careerAdvantage: 'Ability to operate effectively across complex systems and large organisations — rare at senior IC level, essential at executive level.',
      projectCount: 7,
      projects: ['HPE Grommet Design System', 'Data Governance Design Track', 'Cloud Migration Cost Optimiser'],
      rationale: 'Every role you\'ve held has involved building or improving the system around design — not just the artefacts.',
    },
    {
      name: 'Strategic Leadership',
      confidence: 92,
      evidence: 'Scaled a design team 8x at Accenture, founded first-ever design capability at Photon, drove RFPs with 100% conversion rate',
      careerAdvantage: 'Consistently trusted with undefined problems requiring building from scratch — the defining capability of a design executive.',
      projectCount: 5,
      projects: ['Cloud Migration Cost Optimiser', 'Data Governance Design Track', 'Photon Design Capability'],
      rationale: 'The 8x team scaling at Accenture is not an operational achievement — it\'s evidence of your ability to make the case for design at a leadership level.',
    },
    {
      name: 'AI-Driven Experience Design',
      confidence: 88,
      evidence: 'Anchoring Generative AI cohort of 20+ designers, researching LLMs for conversational experiences',
      careerAdvantage: 'Positions you in the top 5% of enterprise designers globally on the most in-demand emerging capability.',
      projectCount: 3,
      projects: ['Generative AI Cohort', 'Data Governance Design Track', 'AI-powered Business Insights'],
      rationale: 'You are one of the very few designers who has moved from curiosity about AI to active capability-building at enterprise scale.',
    },
    {
      name: 'Cross-Cultural Navigation',
      confidence: 85,
      evidence: 'Led international user research at HPE, designed for Middle Eastern airline, global workshop facilitation',
      careerAdvantage: 'Enables you to lead design for global products and diverse stakeholder groups without needing translation layers.',
      projectCount: 4,
      projects: ['Middle Eastern Airline Booking App', 'HPE Cloud Management Suite'],
      rationale: 'You\'ve consistently designed for audiences you didn\'t grow up with — and done it through research-led empathy.',
    },
    {
      name: 'High-Impact Delivery',
      confidence: 90,
      evidence: '92% engagement boost on airline app, $446K cost savings, 100% RFP conversion, 30% cloud cost optimisation',
      careerAdvantage: 'You speak the language of business outcomes — a critical differentiator when making the case for design investment at board level.',
      projectCount: 6,
      projects: ['Middle Eastern Airline Booking App', 'Telecom Multi-Channel Enterprise App', 'Cloud Migration Cost Optimiser'],
      rationale: 'You measure your impact in numbers that matter to the business. This is not common among designers.',
    },
  ],
  interests: [
    {
      name: 'Generative AI',
      frequency: 10,
      evidence: 'Active research into LLMs, cohort of 20+ designers, conversational AI experiences',
      whyItAppears: ['Anchoring Gen AI cohort at Accenture', 'LLM research for product experiences', 'AI-powered business insights delivery', 'Published on AI design capability'],
      marketOutlook: 'Very High Growth',
      futureRelevance: 'Expected to remain one of the highest-growth design specialisations over the next decade due to enterprise AI adoption and agent-based systems.',
    },
    {
      name: 'Design Leadership',
      frequency: 9,
      evidence: 'Team building at scale, CoE setup, mentoring academic and industry designers',
      whyItAppears: ['8x team scaling at Accenture', 'Founded design capability at Photon', 'Mentored 20+ designers formally'],
      marketOutlook: 'High Growth',
      futureRelevance: 'As organisations mature their AI practices, demand for experienced design leaders who can navigate ambiguity is accelerating.',
    },
    {
      name: 'Design Philosophy',
      frequency: 7,
      evidence: 'Talks on Design Lessons from Vedas, 5-chapter series on ancient design concepts',
      whyItAppears: ['5-part Vedas design series', 'DT Summit facilitation', 'Philosophical framing in public talks'],
      marketOutlook: 'Stable',
      futureRelevance: 'A niche but powerful differentiator — design thinkers who can articulate first principles attract followings and institutional trust.',
    },
    {
      name: 'Enterprise Transformation',
      frequency: 8,
      evidence: 'Consistent work in transforming large enterprise design practices across 4 organisations',
      whyItAppears: ['DesignOps builds at 3 companies', 'Data Governance design track', 'Cross-org design culture work'],
      marketOutlook: 'High Growth',
      futureRelevance: 'Legacy enterprises accelerating digital and AI transformation need exactly this experience profile.',
    },
    {
      name: 'Public Speaking',
      frequency: 6,
      evidence: 'DT Summit \'17 & \'18, UX India \'14, articles and talks on design',
      whyItAppears: ['DT Summit facilitator + presenter', 'UX India speaker', 'Written articles on design'],
      marketOutlook: 'Stable',
      futureRelevance: 'Thought leadership compound interest — every talk and article increases inbound opportunities over time.',
    },
  ],
  futurePaths: [
    {
      title: 'VP / Head of Design',
      whyItFits: 'Your 13-year arc has been quietly preparing you for this. You\'ve built design teams, defined capability at scale, and delivered measurable business outcomes. You\'re not growing toward a VP role — you\'re already operating at that altitude.',
      evidence: ['8x team scaling', '100% RFP conversion', 'Data Governance design track leadership', 'Generative AI cohort anchor'],
      opportunitySize: 'established',
      confidence: 92,
      recommendationStatus: 'Strongly Recommended',
      timeline: '12-18 Months',
      marketDemand: 'Very High',
      growthPotential: 'Excellent',
      keyTransitionAreas: ['P&L Ownership', 'C-Suite Communication', 'Org Design at 50+', 'Executive Presence'],
      betArchetype: 'safe',
      betRationale: 'Builds directly on your 13-year leadership track record. Near-term demand for senior design executives is confirmed by Career Alpha market intelligence. This is your highest-confidence move.',
      careerAlphaScore: 92,
      marketOpportunityScore: 88,
      futureResilienceScore: 85,
      learningInvestment: 'low',
      estimatedTransitionMonths: 12,
      careerROIScore: 86,
      whyNotOtherPaths: 'Lower ceiling than the Bold Bet, but higher near-term predictability. Career Alpha recommends this as the anchor path for those who want to de-risk the transition.',
    },
    {
      title: 'AI Design Strategist / CDO',
      whyItFits: 'You are ahead of 95% of designers on AI. You\'re not just using AI tools — you\'re building the frameworks and cohorts that teach others. An AI-native company building for enterprise would find you uniquely valuable.',
      evidence: ['Generative AI cohort of 20+', 'LLM research for conversational experiences', 'AI-powered business insights'],
      opportunitySize: 'emerging',
      confidence: 87,
      recommendationStatus: 'Strongly Recommended',
      timeline: '12-24 Months',
      marketDemand: 'Very High',
      growthPotential: 'Excellent',
      keyTransitionAreas: ['AI Prototyping', 'LLM Fluency', 'AI Ethics in Design', 'Product-Led Growth'],
      betArchetype: 'growth',
      betRationale: 'Your Generative AI cohort work and LLM research experience already position you inside this trajectory. Career Alpha futures analysis rates this domain as highest-growth for senior designers through 2030.',
      careerAlphaScore: 87,
      marketOpportunityScore: 85,
      futureResilienceScore: 93,
      learningInvestment: 'medium',
      estimatedTransitionMonths: 18,
      careerROIScore: 90,
      whyNotOtherPaths: 'Requires more deliberate positioning than the Safe Bet. Career Alpha signals latent capacity — the key is converting internal project experience into external market signal.',
    },
    {
      title: 'Design Educator / Thought Leader',
      whyItFits: 'Your Vedas series, DT Summit talks, and mentor history reveal a consistent drive to synthesise and teach. You don\'t just do — you reflect on what it means.',
      evidence: ['5-chapter Vedas series', 'DT Summit \'17 & \'18 facilitator', 'UX India \'14 speaker'],
      opportunitySize: 'growing',
      confidence: 78,
      recommendationStatus: 'Emerging Opportunity',
      timeline: '18-36 Months',
      marketDemand: 'High',
      growthPotential: 'Strong',
      keyTransitionAreas: ['Curriculum Design', 'Platform Building', 'Community Leadership', 'Content Strategy'],
      betArchetype: 'bold',
      betRationale: 'Your Vedas series, DT Summit facilitation, and 13-year synthesis pattern reveal a consistent drive to teach at scale. Career Alpha human advantage analysis scores your facilitation and synthesis skills as rare and non-automatable.',
      careerAlphaScore: 78,
      marketOpportunityScore: 72,
      futureResilienceScore: 88,
      learningInvestment: 'high',
      estimatedTransitionMonths: 24,
      careerROIScore: 82,
      whyNotOtherPaths: 'Longest horizon and most identity-shift required. Career Alpha rates this as the highest human-advantage path — but it requires building a public platform from the inside out.',
    },
    {
      title: 'Fractional CDO / Consultant',
      whyItFits: 'Your breadth across aviation, cloud, telecom, insurance, and AI gives you the portfolio diversity that large consulting clients pay a premium for.',
      evidence: ['Multiple industry verticals', 'Design CoE setup experience', 'Business development and RFP leadership'],
      opportunitySize: 'growing',
      confidence: 82,
      recommendationStatus: 'Recommended',
      timeline: '6-18 Months',
      marketDemand: 'High',
      growthPotential: 'Strong',
      keyTransitionAreas: ['Personal Branding', 'Client Acquisition', 'Consulting Frameworks', 'Independent Operations'],
      betArchetype: 'growth',
      betRationale: 'Your breadth across five industry verticals and Design CoE setup experience is exactly the portfolio diversity consulting clients pay a premium for. Career Alpha market intelligence confirms growing demand for fractional design executives in India and remote markets.',
      careerAlphaScore: 82,
      marketOpportunityScore: 78,
      futureResilienceScore: 80,
      learningInvestment: 'medium',
      estimatedTransitionMonths: 9,
      careerROIScore: 84,
      whyNotOtherPaths: 'Provides flexibility but trades leadership leverage for portfolio breadth. Career Alpha flags that this path optimises for autonomy, not impact-at-scale.',
    },
  ],
  gaps: [
    {
      pathway: 'VP / Head of Design',
      gapType: 'Positioning Gap',
      currentReadiness: 82,
      futureReadiness: 95,
      currentState: 'Strong internal design leader with proven delivery track record',
      desiredState: 'Recognised VP-level executive with external market visibility',
      requiredCapabilities: ['P&L ownership', 'C-suite executive presence', 'Board-level communication'],
      gapSize: 'small',
      whyItMatters: 'The difference between your current impact and your current title is the single biggest lever you have.',
      timeline: '12-18 months',
      effort: 'Medium — primarily visibility and positioning',
      howToClose: 'Publish thought leadership, seek a VP title in your next move, build relationships with CDOs at peer organisations.',
      objectives: [
        { id: 'pg-1', text: 'Build executive-level portfolio case studies (3 minimum)', completed: false },
        { id: 'pg-2', text: 'Publish 1 thought leadership article on LinkedIn', completed: false },
        { id: 'pg-3', text: 'Speak at 1 design conference in the next 12 months', completed: false },
        { id: 'pg-4', text: 'Connect with 5 CDOs / Heads of Design at peer organisations', completed: false },
        { id: 'pg-5', text: 'Update LinkedIn headline to reflect VP-level positioning', completed: false },
      ],
    },
    {
      pathway: 'VP / Head of Design',
      gapType: 'Visibility Gap',
      currentReadiness: 60,
      futureReadiness: 85,
      currentState: 'Strong internal reputation, limited external brand',
      desiredState: 'Recognised design leader in the broader industry',
      requiredCapabilities: ['Public thought leadership', 'Conference presence', 'LinkedIn authority'],
      gapSize: 'medium',
      whyItMatters: 'External visibility accelerates every executive career move — it turns passive opportunities into active ones.',
      timeline: '6-12 months',
      effort: 'Medium — sustained monthly publishing',
      howToClose: 'One LinkedIn article per month on AI + enterprise design. Speak at one conference in the next 12 months.',
      objectives: [
        { id: 'vg-1', text: 'Publish 1 article per month for 6 months (AI + enterprise design)', completed: false },
        { id: 'vg-2', text: 'Grow LinkedIn followers to 5K through consistent content', completed: false },
        { id: 'vg-3', text: 'Submit speaker proposal to 2 design conferences', completed: false },
        { id: 'vg-4', text: 'Start a newsletter or content series (Design × AI)', completed: false },
      ],
    },
    {
      pathway: 'AI Design Strategist / CDO',
      gapType: 'Skills Gap',
      currentReadiness: 72,
      futureReadiness: 90,
      currentState: 'Strong AI design strategy, limited hands-on AI prototyping',
      desiredState: 'Fluent in AI tools, able to prototype and demonstrate LLM-powered experiences',
      requiredCapabilities: ['Hands-on AI prototyping', 'LLM prompt engineering', 'AI product frameworks'],
      gapSize: 'medium',
      whyItMatters: 'In AI-native companies, CDOs who can prototype earn exponentially more credibility with engineering teams.',
      timeline: '12-24 months',
      effort: 'High — requires active experimentation and side projects',
      howToClose: 'Build 2-3 public AI design projects. Publish the process. Contribute to or advise an AI startup.',
      objectives: [
        { id: 'sg-1', text: 'Build and publish 2 AI design prototypes publicly', completed: false },
        { id: 'sg-2', text: 'Complete an LLM fluency course (e.g. fast.ai or Coursera)', completed: false },
        { id: 'sg-3', text: 'Advise or join an AI startup as design advisor', completed: false },
        { id: 'sg-4', text: 'Document AI design process on Figma Community or GitHub', completed: false },
      ],
    },
    {
      pathway: 'Fractional CDO / Consultant',
      gapType: 'Skills Gap',
      currentReadiness: 70,
      futureReadiness: 88,
      currentState: 'Extensive delivery experience inside organisations',
      desiredState: 'Independent practice with defined offer, clients, and pricing',
      requiredCapabilities: ['Personal brand', 'Client acquisition', 'Contract frameworks'],
      gapSize: 'medium',
      whyItMatters: 'The hardest part of consulting is finding clients. Your existing network is the shortcut.',
      timeline: '6-12 months to first client',
      effort: 'Medium — positioning and network activation',
      howToClose: 'Define your offer in one sentence. Register on Contra. Activate 10 conversations in your network.',
      objectives: [
        { id: 'fc-1', text: 'Define consulting offer in one sentence and test with 3 people', completed: false },
        { id: 'fc-2', text: 'Create profile on Contra or Toptal as fractional CDO', completed: false },
        { id: 'fc-3', text: 'Have 10 exploratory conversations with potential clients', completed: false },
        { id: 'fc-4', text: 'Land first paid engagement (even small — proof of concept)', completed: false },
      ],
    },
  ],
  actions: {
    immediate: [
      {
        title: 'Publish your AI + Design point of view',
        description: 'Write a 1000-word LinkedIn article on what Generative AI means for experience design in enterprise — drawing on your Accenture cohort work. This positions you publicly on the topic you\'re already leading internally.',
        measurable: 'Article published, 500+ impressions within 2 weeks',
        pathway: 'AI Design Strategist / Chief Design Officer — AI-Native Product Company',
        priority: 'high' as const,
        actionType: 'publish' as const,
        howToStart: 'Go to LinkedIn → Write article → Title it "What Generative AI Actually Means for Enterprise UX" → Use the 3 insights from your Accenture cohort as your three sections. Draft in 90 minutes, publish the same day.',
        link: 'https://www.linkedin.com/article/new/',
        linkLabel: 'Start writing on LinkedIn',
        timeEstimate: '2–3 hours',
      },
      {
        title: 'Document your 3 landmark case studies',
        description: 'Write up the airline app (100-day MLP, 92% engagement), the telecom transformation ($446K savings), and the 8x team scaling. Use the "Situation → Action → Result" structure that resonates at VP hiring level.',
        measurable: '3 case studies completed, each under 500 words with a headline metric',
        pathway: 'VP / Head of Design — Global Tech or Consulting Firm',
        priority: 'high' as const,
        actionType: 'project' as const,
        howToStart: 'Open a new Notion page. Create three sections: Airline App, Telecom, Cloud Scale. For each, write one sentence of context, two sentences of what you did, one sentence of result. The metrics are already in your resume — expand from there.',
        link: 'https://www.notion.so',
        linkLabel: 'Open Notion',
        whereToStart: 'Notion or Google Docs — whichever you already use for thinking',
        timeEstimate: '3 hours total (1 per case study)',
      },
      {
        title: 'Build a public AI design prototype',
        description: 'Build and publish one small AI-assisted design tool. A Figma plugin that generates UX audit suggestions via GPT-4 is achievable in a weekend and immediately differentiating.',
        measurable: 'Plugin or prototype live on Figma Community or GitHub with 50+ views',
        pathway: 'AI Design Strategist / Chief Design Officer — AI-Native Product Company',
        priority: 'high' as const,
        actionType: 'project' as const,
        howToStart: 'Start with the Figma Plugin Quickstart template. Use the OpenAI API (model: gpt-4o) to take selected frame content and return UX improvement suggestions. The Figma docs have a working plugin running in under 30 minutes.',
        link: 'https://www.figma.com/plugin-docs/plugin-quickstart-guide/',
        linkLabel: 'Figma Plugin Quickstart Guide',
        whereToStart: 'Figma Community → Plugins → Manage plugins → Create new plugin',
        timeEstimate: '1 weekend (8–12 hours)',
      },
    ],
    mediumTerm: [
      {
        title: 'Launch "Design × AI" newsletter on Substack',
        description: 'A monthly newsletter for senior designers navigating AI — tools, frameworks, and enterprise case studies. Your Vedas series proves you can sustain long-form content. This combines that discipline with your AI expertise.',
        measurable: '12 issues published, 1000+ subscribers within 6 months',
        pathway: 'Design Educator / Thought Leader — Platform or Institution',
        priority: 'high' as const,
        actionType: 'project' as const,
        howToStart: 'Create a free Substack account. Name it "Design × AI" or "Systems + Intelligence". Write issue #1 on "The 3 things I learned leading a 20-person Gen AI design cohort at a global consultancy." Publish it. Share on LinkedIn the same day.',
        link: 'https://substack.com/create',
        linkLabel: 'Create Substack newsletter',
        whereToStart: 'Substack (free to start, takes 10 minutes to set up)',
        timeEstimate: '4 hours for setup + first issue',
      },
      {
        title: 'Pursue VP / Design Director elevation',
        description: 'Either push for an internal VP title at Accenture — you\'re already operating at that level — or identify 5 external target companies where your AI + enterprise background is uniquely valuable.',
        measurable: 'Title change or signed offer letter within 12 months',
        pathway: 'VP / Head of Design — Global Tech or Consulting Firm',
        priority: 'high' as const,
        actionType: 'connect' as const,
        howToStart: 'Search LinkedIn for "Head of Design" or "VP Design" at companies that have had Series C+ funding in the last 18 months AND are building AI products. Filter by India + Remote. Message 5 people in equivalent or adjacent roles for a 20-minute conversation, not a job application.',
        link: 'https://www.linkedin.com/jobs/search/?keywords=VP+Design+AI&f_TPR=r2592000',
        linkLabel: 'Search VP Design + AI roles (LinkedIn)',
        timeEstimate: '2 hours research + 1 hour outreach',
      },
      {
        title: 'Apply for a design advisor role at an AI startup',
        description: 'Find 2-3 early-stage AI startups in India or globally where you can advise 4-8 hours/month. AngelList and YC are the fastest way to find serious teams who need your exact expertise.',
        measurable: 'One advisory agreement signed within 90 days',
        pathway: 'AI Design Strategist / Chief Design Officer — AI-Native Product Company',
        priority: 'medium' as const,
        actionType: 'connect' as const,
        howToStart: 'Go to Wellfound (AngelList) and filter for AI startups in the Seed–Series A stage. Look for companies with no design hire yet or a single junior designer. Message founders directly: "I lead design at Accenture\'s AI practice. I advise 1-2 startups per year. Is this a good time to talk?"',
        link: 'https://wellfound.com/jobs?role=Designer&stage=Seed,Series+A&q=AI',
        linkLabel: 'Browse AI startups on Wellfound',
        timeEstimate: '3 hours research + outreach',
      },
    ],
    longTerm: [
      {
        title: 'Define and launch your fractional CDO offer',
        description: 'Package your experience as a clear consulting offer: "I help Series B-D companies build their design capability from 0 to 1 in 90 days." Your track record is already a complete consulting brochure.',
        measurable: 'First paid consulting engagement completed',
        pathway: 'Independent Design Consultant / Fractional CDO',
        priority: 'medium' as const,
        actionType: 'project' as const,
        howToStart: 'Register on Contra as an independent designer — it\'s specifically built for fractional roles and has a strong design community. Create a profile, describe your offer in one sentence, and list your 3 case study outcomes. It\'s free to start.',
        link: 'https://contra.com/independent',
        linkLabel: 'Create profile on Contra',
        whereToStart: 'Contra (purpose-built for fractional design roles)',
        timeEstimate: '2 hours to set up, ongoing',
      },
      {
        title: 'Create a Design Leadership course with Uxcel',
        description: 'You\'re already a verified top-1% designer on Uxcel. Partner with them to create a course on "Design Leadership in the AI Era." Your existing score gives you a direct in with their content team.',
        measurable: 'Course live with 500+ enrolled in first 3 months',
        pathway: 'Design Educator / Thought Leader — Platform or Institution',
        priority: 'medium' as const,
        actionType: 'connect' as const,
        howToStart: 'Email Uxcel\'s content team at content@uxcel.com — reference your verified top-1% score and propose a 5-module course on AI-led design leadership. Attach your LinkedIn and one case study. They actively look for verified practitioners to create content.',
        link: 'https://uxcel.com',
        linkLabel: 'Go to Uxcel',
        timeEstimate: '1 hour to draft proposal',
      },
    ],
    resources: [
      {
        type: 'book' as const,
        title: 'Org Design for Design Orgs',
        url: 'https://www.amazon.com/Org-Design-Orgs-Peter-Merholz/dp/1491938358',
        pathway: 'VP / Head of Design — Global Tech or Consulting Firm',
        whereToStart: 'Start with Chapter 4 — "Recruiting and Hiring." Directly applicable to the team scaling you\'ve already done.',
        firstStep: 'Buy on Amazon or find on O\'Reilly if your company has a subscription.',
      },
      {
        type: 'book' as const,
        title: 'The Making of a Manager — Julie Zhuo',
        url: 'https://www.amazon.com/Making-Manager-What-Everyone-Looks/dp/0735219567',
        pathway: 'VP / Head of Design — Global Tech or Consulting Firm',
        whereToStart: 'Start with Chapter 7 — "The Art of Feedback." Best for sharpening how you give feedback at scale to a large team.',
        firstStep: 'Available on Audible if you prefer audio during commute.',
      },
      {
        type: 'course' as const,
        title: 'AI for Everyone — Andrew Ng',
        url: 'https://www.coursera.org/learn/ai-for-everyone',
        pathway: 'AI Design Strategist / Chief Design Officer — AI-Native Product Company',
        whereToStart: 'Week 2: "Building AI Projects" — most relevant for someone running an AI design cohort.',
        firstStep: 'Free to audit on Coursera. Takes 6 hours total, do it over a weekend.',
      },
      {
        type: 'community' as const,
        title: 'Contra — Fractional Designer Network',
        url: 'https://contra.com/independent',
        pathway: 'Independent Design Consultant / Fractional CDO',
        firstStep: 'Create a free profile. Browse "Design Strategy" projects to understand what companies are currently paying for.',
      },
      {
        type: 'community' as const,
        title: 'ADPList — Design Leadership Mentoring',
        url: 'https://adplist.org',
        pathway: 'Design Educator / Thought Leader — Platform or Institution',
        firstStep: 'Sign up as a mentor (not a mentee). Your experience qualifies you. It builds your visibility with the next generation of designers who will share your work.',
      },
    ],
  },
  confidenceScores: {
    timeline: 94,
    projects: 88,
    strengths: 91,
    futurePaths: 85,
  },
  insights: [
    'You\'ve quietly built a track record that most design leaders spend their entire career chasing — 8x team scaling, measurable revenue outcomes, and AI capability-building — all in a single role.',
    'Your Vedas series is not a side hustle — it\'s evidence of a rare ability to synthesise philosophy, culture, and design. That\'s a brand asset most designers don\'t even know they\'re missing.',
    'You are operating as a VP-level design leader without the VP title. The gap between your impact and your positioning is the single biggest career opportunity in front of you right now.',
    'Your AI work at Accenture positions you in the top 5% of enterprise designers globally. Most designers are still observing AI from the outside — you\'re building the infrastructure from the inside.',
  ],
  rationale: {
    'Systems Thinking': 'Evidenced across all 4 organisations — Infosys (20+ client accounts with consistent IA practice), Photon (founding design culture), HPE (Grommet.io design system), Accenture (DesignOps and Data Governance frameworks)',
    'AI confidence': 'Based on active cohort leadership of 20+ designers, published research, and Accenture AI product delivery — not just tool adoption',
  },
  positioning: {
    targetRole: 'VP of Design / Head of Design',
    targetCompanies: [
      'Enterprise SaaS companies (Series C+)',
      'AI-first product companies',
      'Global consulting firms (senior design leadership)',
    ],
    targetIdentity: [
      'Strategic Design Leader',
      'AI Transformation Leader',
      'Design Executive',
    ],
    positioningStatement: 'I help organisations navigate complexity through design leadership, systems thinking, and AI-enabled transformation.',
  },
  roadmapMilestones: [
    {
      phase: 'Today',
      actions: [
        'Update LinkedIn headline to reflect VP-level positioning',
        'Rewrite portfolio intro with executive framing',
        'List your 3 highest-impact projects with measurable outcomes',
      ],
      positioningMoves: ['Refresh LinkedIn profile', 'Update portfolio'],
    },
    {
      phase: '30 Days',
      actions: [
        'Publish first AI + enterprise design article on LinkedIn',
        'Create executive resume (1 page, outcome-focused)',
        'Document your 3 landmark case studies (SAR format)',
      ],
      hardSkills: ['Resume writing', 'Case study documentation'],
      softSkills: ['Executive communication'],
    },
    {
      phase: '90 Days',
      actions: [
        'Build and publish one public AI design prototype',
        'Submit speaker proposal to 2 design conferences',
        'Connect with 5 CDOs / Heads of Design at peer firms',
      ],
      hardSkills: ['AI prototyping', 'Figma plugin development'],
      positioningMoves: ['Speaking applications', 'Executive networking'],
    },
    {
      phase: '6 Months',
      actions: [
        'Speak at one conference or lead a public workshop',
        'Grow LinkedIn to 5K followers through consistent content',
        'Launch "Design × AI" newsletter (500+ subscribers)',
      ],
      softSkills: ['Thought leadership', 'Public speaking'],
      positioningMoves: ['Content authority building'],
    },
    {
      phase: '12 Months',
      actions: [
        'Secure VP / Head of Design title (internal or external)',
        'Formalise one advisory role with an AI startup',
        'Reach 1K newsletter subscribers',
      ],
      positioningMoves: ['Title elevation', 'Advisory positioning'],
    },
    {
      phase: '18 Months',
      actions: [
        'Industry recognition as an AI design thought leader',
        'Active advisory portfolio (2-3 companies)',
        'First fractional CDO engagement (if pursuing)',
      ],
      positioningMoves: ['Institutional recognition', 'Consulting practice'],
    },
  ],
  careerAlpha: {
    careerStage: 'senior' as const,
    archetypeLabel: 'Seasoned Enterprise Design Leader',
    archetypeFingerprint: 'senior-ux-design-india-ai-design-leadership',
    overallScore: 84,
    synthesis: 'Your 13-year track record spanning enterprise, consumer, and AI-powered products positions you at the rare intersection of strategic design leadership and emerging AI capability. Clear signals suggest the market is moving toward your strengths faster than most peers are equipped to follow.',
    weightingRationale: 'Intrinsic signal carries high weight given 13 years of rich evidence. Market intelligence amplifies this — enterprise AI design demand is at an inflection point.',
    methodSummary: 'Career Alpha analyses your professional footprint across five dimensions: your personal evidence (intrinsic signal), current market demand for your archetype, futures research on where your domain is heading, your human advantage relative to AI automation, and the ROI of potential career transitions.',
    observations: [
      '13 years of enterprise design detected',
      'Strong systems thinking pattern across 4 industries',
      'AI/automation risk: low for this archetype',
      'High demand signal in enterprise AI design roles',
    ],
    dimensions: {
      intrinsicSignal: {
        insight: 'Your track record strongly indicates a rare combination: you ship at scale (100-day MLP, 8x team growth) while simultaneously advancing design system maturity and AI capability. This pattern of execution-plus-elevation is a defining career signal.',
        signals: ['100-day MLP airline app', '8x team scaling at Accenture', 'HPE Grommet co-definition', 'Data Governance AI track'],
        cached_at: '2026-07-11',
        confidenceScore: 88,
      },
      marketIntelligence: {
        insight: 'Clear signals suggest enterprise AI design leadership is entering an inflection point. Companies scaling AI products are discovering a critical shortage of designers who understand both design systems and AI interaction patterns — your exact positioning.',
        signals: ['Enterprise AI design roles up 40% YoY', 'India tech sector AI investment surge', 'Remote senior design roles growing'],
        cached_at: '2026-07-11',
        confidenceScore: 78,
      },
      futuresAnalysis: {
        insight: 'WEF and McKinsey research consistently identifies human-AI collaboration design as one of the highest-growth adjacent roles through 2030. Your work at Accenture on AI-powered business insights already places you inside this trajectory.',
        signals: ['WEF Future of Jobs 2025', 'McKinsey State of AI 2024', 'Oxford automation probability models'],
        cached_at: '2026-07-11',
        confidenceScore: 72,
      },
      humanAdvantageIndex: {
        insight: 'Your advantage compounds at the intersection of systems thinking, stakeholder facilitation, and AI literacy. These are precisely the capabilities that AI augments rather than replaces — and they become more valuable as AI handles more execution work.',
        signals: ['Cross-industry facilitation pattern', 'Design system co-authorship', 'Multi-stakeholder enterprise projects'],
        cached_at: '2026-07-11',
        confidenceScore: 82,
      },
      careerROI: {
        insight: 'A move toward AI Design Leadership from your current position requires low transition effort (you already have the foundation) with disproportionate upside. Estimated 6-9 months to fully reposition, with senior IC to Director-equivalent roles within 18 months.',
        signals: ['Current AI project exposure', 'Existing leadership track record', 'Design system depth'],
        cached_at: '2026-07-11',
        confidenceScore: 75,
      },
    },
  } satisfies CareerAlphaIntelligence,
}
