// lib/mock-data.ts
// Mock data based on Amit Kumar Tiwari's resume — used when NEXT_PUBLIC_MOCK=true

import { ExtractedCareerData, Blueprint } from '@/types/wingspan'

export const mockExtractedData: ExtractedCareerData = {
  timeline: [
    {
      id: '1',
      role: 'UX Manager',
      company: 'Accenture',
      startDate: 'Dec 2018',
      endDate: 'Present',
      description: 'Leading Data Governance design track for global Data & AI capability. Led 8x team scaling, airline booking app, telecom enterprise, AI-powered business insights, new insurance app launch.',
      confirmed: false,
    },
    {
      id: '2',
      role: 'UX Design Engineer',
      company: 'Hewlett Packard Enterprise',
      startDate: 'Dec 2015',
      endDate: 'Dec 2018',
      description: 'Designed composable and hybrid cloud management products. Co-defined HPE design system (Grommet.io). Led international user research and usability testing.',
      confirmed: false,
    },
    {
      id: '3',
      role: 'UX Creative Lead',
      company: 'Photon Interactive',
      startDate: 'Jul 2014',
      endDate: 'Dec 2015',
      description: 'E2E design for B2C e-commerce for a leading global publishing group. Founded first-ever design capability and local chapter.',
      confirmed: false,
    },
    {
      id: '4',
      role: 'UX Designer',
      company: 'Infosys Limited',
      startDate: 'Jan 2011',
      endDate: 'Jul 2014',
      description: 'Worked for 20+ client accounts conducting user-research, contextual enquiry, information architecture, low-fi and hi-fi prototyping and visual design.',
      confirmed: false,
    },
  ],
  projects: [
    {
      id: 'p1',
      name: 'Middle Eastern Airline Booking App',
      company: 'Accenture',
      year: '2022',
      industry: 'Aviation',
      platform: 'Mobile',
      audience: 'B2C',
      summary: 'End-to-end experience design for a major Middle Eastern airline booking app',
      impact: '100-day MLP launch, 300K new visitors, 92% engagement boost',
    },
    {
      id: 'p2',
      name: 'Data Governance Design Track',
      company: 'Accenture',
      year: '2023',
      industry: 'Data & AI',
      platform: 'Enterprise',
      audience: 'B2B',
      summary: 'AI-powered business insights for 360° value proposition',
      impact: 'RFPs resulting in 100% conversion',
    },
    {
      id: 'p3',
      name: 'Telecom Multi-Channel Enterprise App',
      company: 'Accenture',
      year: '2021',
      industry: 'Telecom',
      platform: 'Web',
      audience: 'B2B',
      summary: 'Experience strategy for multi-channel enterprise business',
      impact: '$446K in cost savings',
    },
    {
      id: 'p4',
      name: 'Cloud Migration Cost Optimiser',
      company: 'Accenture',
      year: '2022',
      industry: 'Cloud',
      platform: 'Enterprise SaaS',
      audience: 'B2B',
      summary: 'Scaled design team 8x for cloud product',
      impact: 'Optimises cloud migration costs by nearly 30%',
    },
    {
      id: 'p5',
      name: 'New Insurance App',
      company: 'Accenture',
      year: '2023',
      industry: 'Insurance',
      platform: 'Mobile',
      audience: 'B2C',
      summary: 'Design and launch of insurance app for Indian consumers',
      impact: 'Catering to diverse user base',
    },
    {
      id: 'p6',
      name: 'HPE Cloud Management Suite',
      company: 'Hewlett Packard Enterprise',
      year: '2017',
      industry: 'Cloud',
      platform: 'Enterprise SaaS',
      audience: 'B2B',
      summary: 'Composable and hybrid cloud management products',
      impact: 'Improved product adoption through cross-collaborative design practices',
    },
    {
      id: 'p7',
      name: 'HPE Grommet Design System',
      company: 'Hewlett Packard Enterprise',
      year: '2016',
      industry: 'Design Systems',
      platform: 'Web',
      audience: 'B2B',
      summary: 'Co-defined key components for HPE\'s design system (Grommet.io)',
      impact: 'Impacted brand consistency and efficiency across HPE products',
    },
  ],
  skills: [
    'Experience Strategy', 'Design Leadership', 'UX Research', 'Information Architecture',
    'Wireframing', 'Prototyping', 'Usability Testing', 'Design Systems', 'DesignOps',
    'Generative AI', 'Product Mindset', 'MLP Definition', 'Figma', 'Framer', 'Adobe CC',
    'Miro', 'FigJam', 'JIRA', 'Notion', 'Google Analytics', 'Stakeholder Management',
    'Team Building', 'Mentoring', 'Workshop Facilitation',
  ],
  education: [
    { institution: 'West Bengal University of Technology', degree: 'Bachelor of Technology, Computer Science & Engg', year: '2010' },
    { institution: 'UXCEL', degree: 'UX Designer Certification — Verified Designer, score 99 (Top 1% worldwide)', year: '2022' },
    { institution: 'Google Coursera', degree: 'Foundation of UX', year: '2022' },
    { institution: 'UX Academy (Infosys)', degree: 'UX Certification', year: '2012' },
  ],
  rawText: 'Amit Kumar Tiwari — UX Manager with 13+ years of experience across Accenture, HPE, Photon Interactive, and Infosys.',
}

export const mockBlueprint: Blueprint = {
  profileMap: {
    identityStatement: 'You are a rare hybrid — a design strategist who thinks like a product leader and builds like an engineer. Over 13 years, you\'ve consistently operated at the intersection of complexity, systems, and human experience.',
    yearsOfExperience: 13,
    industries: ['Data & AI', 'Aviation', 'Cloud', 'Telecom', 'Insurance', 'FinTech', 'E-commerce'],
    platforms: ['Enterprise SaaS', 'Mobile', 'Web', 'Design Systems'],
    domains: ['Experience Strategy', 'Design Leadership', 'Generative AI', 'DesignOps', 'Product Design'],
    careerEvolution: 'You began as a craftsman of interfaces at Infosys, sharpened into a creative lead at Photon, then stepped fully into strategic territory at HPE building foundational design systems. At Accenture, you\'ve evolved into a design executive — scaling teams, defining capability, and anchoring AI-first experiences for global enterprises. Your arc is unmistakably upward: from hands-on design to organisational transformation.',
  },
  strengths: [
    {
      name: 'Systems Thinking',
      confidence: 95,
      evidence: 'Co-defined Grommet.io at HPE, anchored Data Governance design track at Accenture, built DesignOps frameworks across 4 organisations',
      projectCount: 7,
      projects: ['HPE Grommet Design System', 'Data Governance Design Track', 'Cloud Migration Cost Optimiser'],
      rationale: 'Every role you\'ve held has involved building or improving the system around design — not just the artefacts. You don\'t just design products, you design the conditions in which great design happens. This pattern appears in every organisation you\'ve joined.',
    },
    {
      name: 'Strategic Leadership',
      confidence: 92,
      evidence: 'Scaled a design team 8x at Accenture, founded first-ever design capability at Photon, drove RFPs with 100% conversion rate',
      projectCount: 5,
      projects: ['Cloud Migration Cost Optimiser', 'Data Governance Design Track', 'Photon Design Capability'],
      rationale: 'You are consistently trusted with undefined problems that require building from scratch. The 8x team scaling at Accenture is not an operational achievement — it\'s evidence of your ability to make the case for design at a leadership level and deliver on it.',
    },
    {
      name: 'AI-Driven Experience Design',
      confidence: 88,
      evidence: 'Anchoring Generative AI cohort of 20+ designers, researching LLMs for conversational experiences, AI-powered business insights for Accenture',
      projectCount: 3,
      projects: ['Generative AI Cohort', 'Data Governance Design Track', 'AI-powered Business Insights'],
      rationale: 'You are one of the very few designers who has moved from curiosity about AI to active capability-building. You are not waiting for AI to define design — you are defining what AI-enabled design looks like inside a major consultancy.',
    },
    {
      name: 'Cross-Cultural & Complex Stakeholder Navigation',
      confidence: 85,
      evidence: 'Led international user research at HPE, designed for Middle Eastern airline, delivered workshops with global participants',
      projectCount: 4,
      projects: ['Middle Eastern Airline Booking App', 'HPE Cloud Management Suite', 'Telecom Multi-Channel Enterprise App'],
      rationale: 'Your work has spanned India, Middle East, and global enterprise contexts. You\'ve consistently designed for audiences you didn\'t grow up with — and done it through research-led empathy rather than assumption.',
    },
    {
      name: 'High-Impact Delivery',
      confidence: 90,
      evidence: '92% engagement boost on airline app, $446K cost savings, 100% RFP conversion, 30% cloud cost optimisation',
      projectCount: 6,
      projects: ['Middle Eastern Airline Booking App', 'Telecom Multi-Channel Enterprise App', 'Cloud Migration Cost Optimiser'],
      rationale: 'You measure your impact in numbers that matter to the business. This is not common among designers — most speak in qualitative outcomes. Your ability to connect design decisions to revenue, conversion, and cost demonstrates a fundamentally commercial mindset.',
    },
  ],
  interests: [
    { name: 'Generative AI', frequency: 10, evidence: 'Active research into LLMs, cohort of 20+ designers, conversational AI experiences' },
    { name: 'Design Leadership', frequency: 9, evidence: 'Team building at scale, CoE setup, mentoring academic and industry designers' },
    { name: 'Philosophy & Design', frequency: 7, evidence: 'Talks on Design Lessons from Vedas, 5-chapter series on ancient design concepts' },
    { name: 'Enterprise Transformation', frequency: 8, evidence: 'Consistent work in transforming large enterprise design practices' },
    { name: 'Public Speaking', frequency: 6, evidence: 'DT Summit \'17 & \'18, UX India \'14, articles and talks on design' },
    { name: 'Design Systems', frequency: 7, evidence: 'Grommet.io at HPE, DesignOps across multiple organisations' },
  ],
  futurePaths: [
    {
      title: 'VP / Head of Design — Global Tech or Consulting Firm',
      whyItFits: 'Your 13-year arc has been quietly preparing you for this. You\'ve built design teams, defined capability at scale, and delivered measurable business outcomes. You\'re not growing toward a VP role — you\'re already operating at that altitude at Accenture. The next move is the title catching up with the reality.',
      evidence: ['8x team scaling', '100% RFP conversion', 'Data Governance design track leadership', 'Generative AI cohort anchor'],
      opportunitySize: 'established',
      confidence: 92,
    },
    {
      title: 'AI Design Strategist / Chief Design Officer — AI-Native Product Company',
      whyItFits: 'You are ahead of 95% of designers on AI. You\'re not just using AI tools — you\'re building the frameworks and cohorts that teach others how to use them strategically. An AI-native product company building for enterprise would find you uniquely valuable as someone who understands both the technical landscape and the human experience layer.',
      evidence: ['Generative AI cohort of 20+', 'LLM research for conversational experiences', 'AI-powered business insights work'],
      opportunitySize: 'emerging',
      confidence: 87,
    },
    {
      title: 'Design Educator / Thought Leader — Platform or Institution',
      whyItFits: 'Your Vedas series, DT Summit talks, UX India presentations, and mentor history reveal a consistent drive to synthesise and teach. You don\'t just do — you reflect on what it means. This is rare, and it\'s the foundation of a powerful design education platform or a university design leadership program.',
      evidence: ['5-chapter Vedas series', 'DT Summit \'17 & \'18 facilitator', 'UX India \'14 speaker', 'Academic mentoring'],
      opportunitySize: 'growing',
      confidence: 78,
    },
    {
      title: 'Independent Design Consultant / Fractional CDO',
      whyItFits: 'Your breadth across aviation, cloud, telecom, insurance, and AI gives you the portfolio diversity that large consulting clients pay a premium for. As a fractional CDO, you could serve 2-3 high-growth companies simultaneously, setting up their design capability the way you\'ve done repeatedly inside larger organisations.',
      evidence: ['Multiple industry verticals', 'Design CoE setup experience', 'Business development and RFP leadership'],
      opportunitySize: 'growing',
      confidence: 82,
    },
  ],
  gaps: [
    {
      pathway: 'VP / Head of Design — Global Tech or Consulting Firm',
      currentReadiness: 82,
      futureReadiness: 95,
      requiredCapabilities: ['P&L ownership', 'C-suite executive presence', 'Board-level communication', 'Org design at 50+ people'],
      gapSize: 'small',
      timeline: '12-18 months',
      effort: 'Medium — primarily visibility and positioning',
      howToClose: 'You already have the skills. The gap is positioning and visibility at the executive level. Focus on publishing thought leadership on LinkedIn around AI and design leadership, seek a formal VP or Design Director title in your next internal or external move, and build relationships with CDOs at peer organisations.',
    },
    {
      pathway: 'AI Design Strategist / Chief Design Officer — AI-Native Product Company',
      currentReadiness: 72,
      futureReadiness: 90,
      requiredCapabilities: ['Hands-on AI prototyping', 'LLM prompt engineering fluency', 'Product-led growth understanding', 'Startup operating context'],
      gapSize: 'medium',
      timeline: '12-24 months',
      effort: 'High — requires active experimentation and side projects',
      howToClose: 'Build 2-3 public AI design projects — tools, prototypes, or case studies that demonstrate you can work with AI, not just talk about it. Publish the process openly. Consider contributing to or advising an AI startup to get startup operating experience alongside your enterprise background.',
    },
    {
      pathway: 'Design Educator / Thought Leader — Platform or Institution',
      currentReadiness: 65,
      futureReadiness: 85,
      requiredCapabilities: ['Curriculum design', 'Online community building', 'Content platform strategy', 'Monetisation models'],
      gapSize: 'medium',
      timeline: '18-36 months',
      effort: 'High — sustained content and community investment',
      howToClose: 'Start a focused newsletter or YouTube series on AI-driven design leadership — combining your two strongest areas. Aim for one substantive public piece per month. Partner with existing design education platforms (like Uxcel, where you\'re already verified) to create content or courses.',
    },
    {
      pathway: 'Independent Design Consultant / Fractional CDO',
      currentReadiness: 70,
      futureReadiness: 88,
      requiredCapabilities: ['Personal brand', 'Business development without institutional backing', 'Contract and pricing frameworks', 'Client acquisition'],
      gapSize: 'medium',
      timeline: '6-12 months to first client',
      effort: 'Medium — positioning and network activation',
      howToClose: 'Define your consulting offer clearly: "I help Series B-D companies build their design capability from 0 to 1." Start with your existing network at HPE and Accenture alumni. Your track record of 8x team scaling, 100% RFP conversion, and $446K savings is already a compelling consulting case study.',
    },
  ],
  actions: {
    immediate: [
      {
        title: 'Publish your AI + Design point of view',
        description: 'Write a 1000-word LinkedIn article on what Generative AI means for experience design in enterprise — drawing on your Accenture cohort work. This positions you publicly on the topic you\'re already leading internally.',
        measurable: 'Article published, 500+ impressions within 2 weeks',
        pathway: 'AI Design Strategist / Chief Design Officer — AI-Native Product Company',
        priority: 'high' as const,
        actionType: 'publish' as const,
        howToStart: 'Go to LinkedIn → Write article → Title it "What Generative AI Actually Means for Enterprise UX" → Use the 3 insights from your Accenture cohort as your three sections. Draft in 90 minutes, publish the same day.',
        link: 'https://www.linkedin.com/article/new/',
        linkLabel: 'Start writing on LinkedIn',
        timeEstimate: '2–3 hours',
      },
      {
        title: 'Document your 3 landmark case studies',
        description: 'Write up the airline app (100-day MLP, 92% engagement), the telecom transformation ($446K savings), and the 8x team scaling. Use the "Situation → Action → Result" structure that resonates at VP hiring level.',
        measurable: '3 case studies completed, each under 500 words with a headline metric',
        pathway: 'VP / Head of Design — Global Tech or Consulting Firm',
        priority: 'high' as const,
        actionType: 'project' as const,
        howToStart: 'Open a new Notion page. Create three sections: Airline App, Telecom, Cloud Scale. For each, write one sentence of context, two sentences of what you did, one sentence of result. The metrics are already in your resume — expand from there.',
        link: 'https://www.notion.so',
        linkLabel: 'Open Notion',
        whereToStart: 'Notion or Google Docs — whichever you already use for thinking',
        timeEstimate: '3 hours total (1 per case study)',
      },
      {
        title: 'Build a public AI design prototype',
        description: 'Build and publish one small AI-assisted design tool. A Figma plugin that generates UX audit suggestions via GPT-4 is achievable in a weekend and immediately differentiating.',
        measurable: 'Plugin or prototype live on Figma Community or GitHub with 50+ views',
        pathway: 'AI Design Strategist / Chief Design Officer — AI-Native Product Company',
        priority: 'high' as const,
        actionType: 'project' as const,
        howToStart: 'Start with the Figma Plugin Quickstart template. Use the OpenAI API (model: gpt-4o) to take selected frame content and return UX improvement suggestions. The Figma docs have a working plugin running in under 30 minutes.',
        link: 'https://www.figma.com/plugin-docs/plugin-quickstart-guide/',
        linkLabel: 'Figma Plugin Quickstart Guide',
        whereToStart: 'Figma Community → Plugins → Manage plugins → Create new plugin',
        timeEstimate: '1 weekend (8–12 hours)',
      },
    ],
    mediumTerm: [
      {
        title: 'Launch "Design × AI" newsletter on Substack',
        description: 'A monthly newsletter for senior designers navigating AI — tools, frameworks, and enterprise case studies. Your Vedas series proves you can sustain long-form content. This combines that discipline with your AI expertise.',
        measurable: '12 issues published, 1000+ subscribers within 6 months',
        pathway: 'Design Educator / Thought Leader — Platform or Institution',
        priority: 'high' as const,
        actionType: 'project' as const,
        howToStart: 'Create a free Substack account. Name it "Design × AI" or "Systems + Intelligence". Write issue #1 on "The 3 things I learned leading a 20-person Gen AI design cohort at a global consultancy." Publish it. Share on LinkedIn the same day.',
        link: 'https://substack.com/create',
        linkLabel: 'Create Substack newsletter',
        whereToStart: 'Substack (free to start, takes 10 minutes to set up)',
        timeEstimate: '4 hours for setup + first issue',
      },
      {
        title: 'Pursue VP / Design Director elevation',
        description: 'Either push for an internal VP title at Accenture — you\'re already operating at that level — or identify 5 external target companies where your AI + enterprise background is uniquely valuable.',
        measurable: 'Title change or signed offer letter within 12 months',
        pathway: 'VP / Head of Design — Global Tech or Consulting Firm',
        priority: 'high' as const,
        actionType: 'connect' as const,
        howToStart: 'Search LinkedIn for "Head of Design" or "VP Design" at companies that have had Series C+ funding in the last 18 months AND are building AI products. Filter by India + Remote. Message 5 people in equivalent or adjacent roles for a 20-minute conversation, not a job application.',
        link: 'https://www.linkedin.com/jobs/search/?keywords=VP+Design+AI&f_TPR=r2592000',
        linkLabel: 'Search VP Design + AI roles (LinkedIn)',
        timeEstimate: '2 hours research + 1 hour outreach',
      },
      {
        title: 'Apply for a design advisor role at an AI startup',
        description: 'Find 2-3 early-stage AI startups in India or globally where you can advise 4-8 hours/month. AngelList and YC are the fastest way to find serious teams who need your exact expertise.',
        measurable: 'One advisory agreement signed within 90 days',
        pathway: 'AI Design Strategist / Chief Design Officer — AI-Native Product Company',
        priority: 'medium' as const,
        actionType: 'connect' as const,
        howToStart: 'Go to Wellfound (AngelList) and filter for AI startups in the Seed–Series A stage. Look for companies with no design hire yet or a single junior designer. Message founders directly: "I lead design at Accenture\'s AI practice. I advise 1-2 startups per year. Is this a good time to talk?"',
        link: 'https://wellfound.com/jobs?role=Designer&stage=Seed,Series+A&q=AI',
        linkLabel: 'Browse AI startups on Wellfound',
        timeEstimate: '3 hours research + outreach',
      },
    ],
    longTerm: [
      {
        title: 'Define and launch your fractional CDO offer',
        description: 'Package your experience as a clear consulting offer: "I help Series B-D companies build their design capability from 0 to 1 in 90 days." Your track record is already a complete consulting brochure.',
        measurable: 'First paid consulting engagement completed',
        pathway: 'Independent Design Consultant / Fractional CDO',
        priority: 'medium' as const,
        actionType: 'project' as const,
        howToStart: 'Register on Contra as an independent designer — it\'s specifically built for fractional roles and has a strong design community. Create a profile, describe your offer in one sentence, and list your 3 case study outcomes. It\'s free to start.',
        link: 'https://contra.com/independent',
        linkLabel: 'Create profile on Contra',
        whereToStart: 'Contra (purpose-built for fractional design roles)',
        timeEstimate: '2 hours to set up, ongoing',
      },
      {
        title: 'Create a Design Leadership course with Uxcel',
        description: 'You\'re already a verified top-1% designer on Uxcel. Partner with them to create a course on "Design Leadership in the AI Era." Your existing score gives you a direct in with their content team.',
        measurable: 'Course live with 500+ enrolled in first 3 months',
        pathway: 'Design Educator / Thought Leader — Platform or Institution',
        priority: 'medium' as const,
        actionType: 'connect' as const,
        howToStart: 'Email Uxcel\'s content team at content@uxcel.com — reference your verified top-1% score and propose a 5-module course on AI-led design leadership. Attach your LinkedIn and one case study. They actively look for verified practitioners to create content.',
        link: 'https://uxcel.com',
        linkLabel: 'Go to Uxcel',
        timeEstimate: '1 hour to draft proposal',
      },
    ],
    resources: [
      {
        type: 'book' as const,
        title: 'Org Design for Design Orgs',
        url: 'https://www.amazon.com/Org-Design-Orgs-Peter-Merholz/dp/1491938358',
        pathway: 'VP / Head of Design — Global Tech or Consulting Firm',
        whereToStart: 'Start with Chapter 4 — "Recruiting and Hiring." Directly applicable to the team scaling you\'ve already done.',
        firstStep: 'Buy on Amazon or find on O\'Reilly if your company has a subscription.',
      },
      {
        type: 'book' as const,
        title: 'The Making of a Manager — Julie Zhuo',
        url: 'https://www.amazon.com/Making-Manager-What-Everyone-Looks/dp/0735219567',
        pathway: 'VP / Head of Design — Global Tech or Consulting Firm',
        whereToStart: 'Start with Chapter 7 — "The Art of Feedback." Best for sharpening how you give feedback at scale to a large team.',
        firstStep: 'Available on Audible if you prefer audio during commute.',
      },
      {
        type: 'course' as const,
        title: 'AI for Everyone — Andrew Ng',
        url: 'https://www.coursera.org/learn/ai-for-everyone',
        pathway: 'AI Design Strategist / Chief Design Officer — AI-Native Product Company',
        whereToStart: 'Week 2: "Building AI Projects" — most relevant for someone running an AI design cohort.',
        firstStep: 'Free to audit on Coursera. Takes 6 hours total, do it over a weekend.',
      },
      {
        type: 'community' as const,
        title: 'Contra — Fractional Designer Network',
        url: 'https://contra.com/independent',
        pathway: 'Independent Design Consultant / Fractional CDO',
        firstStep: 'Create a free profile. Browse "Design Strategy" projects to understand what companies are currently paying for.',
      },
      {
        type: 'community' as const,
        title: 'ADPList — Design Leadership Mentoring',
        url: 'https://adplist.org',
        pathway: 'Design Educator / Thought Leader — Platform or Institution',
        firstStep: 'Sign up as a mentor (not a mentee). Your experience qualifies you. It builds your visibility with the next generation of designers who will share your work.',
      },
    ],
  },
  confidenceScores: {
    timeline: 94,
    projects: 88,
    strengths: 91,
    futurePaths: 85,
  },
  insights: [
    'You\'ve quietly built a track record that most design leaders spend their entire career chasing — 8x team scaling, measurable revenue outcomes, and AI capability-building — all in a single role.',
    'Your Vedas series is not a side hustle — it\'s evidence of a rare ability to synthesise philosophy, culture, and design. That\'s a brand asset most designers don\'t even know they\'re missing.',
    'You are operating as a VP-level design leader without the VP title. The gap between your impact and your positioning is the single biggest career opportunity in front of you right now.',
    'Your AI work at Accenture positions you in the top 5% of enterprise designers globally. Most designers are still observing AI from the outside — you\'re building the infrastructure from the inside.',
  ],
  rationale: {
    'Systems Thinking': 'Evidenced across all 4 organisations — Infosys (20+ client accounts with consistent IA practice), Photon (founding design culture), HPE (Grommet.io design system), Accenture (DesignOps and Data Governance frameworks)',
    'AI confidence': 'Based on active cohort leadership of 20+ designers, published research, and Accenture AI product delivery — not just tool adoption',
  },
}
